### ISSUE TITLE
Digital Inputs ampliation

### ISSUE THREAD

**Issue by ghost** [Greeds74/STM32_PLC#1]
I am testing on a STM32F103RBT6 and it works perfectly. Is it possible to increase digital inputs to take advantage of the pins offered by this mcu?

http://www.datasheetdir.com/STM32F103RBT6+ARM

thanks for your work

**Comment by Greeds74** [comment]
Thank you for your interest in our project.Yes, it is quite possible to increase - most likely, this will be done in the next release.
